#ifndef HW_CAMERA_H
#define HW_CAMERA_H

#define CAMERA_I2C 1

#define CAMERA_GPIO_POWER_ON 0x605
#define CAMERA_GPIO_STANDBY 0xA01
#define CAMERA_GPIO_RESET 0xA02
#define CAMERA_GPIO_CLOCK_ENABLE 0xA00

#define CAMERA_ADDR 0x78

#endif
