#ifndef HW_UART_H
#define HW_UART_H

#include "hardware/s5l8900.h"

// Registers
#define NUM_UARTS 5

#define UART_POLL_MODE 0

#define UART_CLOCK_SELECTION_MASK (0x3 << 10) // Bit 10-11
#define UART_CLOCK_SELECTION_SHIFT 10 // Bit 10-11
#define UART_UCON_UNKMASK 0x7000
#define UART_UCON_LOOPBACKMODE (0x1 << 5)
#define UART_UCON_RXMODE_SHIFT 0
#define UART_UCON_RXMODE_MASK (0x3 << UART_UCON_RXMODE_SHIFT)
#define UART_UCON_TXMODE_SHIFT 2
#define UART_UCON_TXMODE_MASK (0x3 << UART_UCON_TXMODE_SHIFT)

#define UART_DIVVAL_MASK 0x0000FFFF
#define UART_SAMPLERATE_MASK 0x00030000 // Bit 5-6
#define UART_SAMPLERATE_SHIFT 4

#define UART_UCON_MODE_DISABLE 0
#define UART_UCON_MODE_IRQORPOLL 1
#define UART_UCON_MODE_DMA0 2
#define UART_UCON_MODE_DMA1 3

#define UART_CLOCK_PCLK 0
#define UART_CLOCK_EXT_UCLK0 1
#define UART_CLOCK_EXT_UCLK1 3

#define UART_SAMPLERATE_4 2
#define UART_SAMPLERATE_8 1
#define UART_SAMPLERATE_16 0

#define UART_UMCON_AFC_BIT 0x10
#define UART_UMCON_NRTS_BIT 0x1

#define UART_5BITS 0
#define UART_6BITS 1
#define UART_7BITS 2
#define UART_8BITS 3

#endif

