#ifndef HW_USB_H
#define HW_USB_H

#include "hardware/s5l8900.h"

// Device
#define USB 0x38400000
#define USB_PHY 0x3C400000

// Registers
#define OPHYPWR 0
#define OPHYCLK 0x4
#define ORSTCON 0x8
#define GOTGCTL 0x0
#define GRSTCTL 0x10
#define GINTSTS 0x14
#define GINTMSK 0x18
#define DIEPMSK 0x810
#define DOEPMSK 0x814
#define USB_INREGS 0x900
#define USB_OUTREGS 0xB00

#define DCFG 0x800
#define DCTL 0x804
#define DSTS 0x808

#define USB_ENDPOINT_DIRECTIONS 0x44
#define USB_ONOFF 0xE00

// Values
#define USB_INTERRUPT 0x13

#define USB_OTGCLOCKGATE 0x2
#define USB_PHYCLOCKGATE 0x23
#define USB_ONOFF_OFF 3	// bits 0, 1

#define OPHYPWR_FORCESUSPEND 0x1
#define OPHYPWR_PLLPOWERDOWN 0x2
#define OPHYPWR_XOPOWERDOWN 0x4
#define OPHYPWR_ANALOGPOWERDOWN 0x8
#define OPHYPWR_UNKNOWNPOWERDOWN 0x10
#define OPHYPWR_POWERON 0x0	// all the previous flags are off

#define OPHYCLK_CLKSEL_MASK 0x3
#define OPHYCLK_CLKSEL_48MHZ 0x0
#define OPHYCLK_CLKSEL_12MHZ 0x2
#define OPHYCLK_CLKSEL_24MHZ 0x3

#define GOTGCTL_BSESSIONVALID (1 << 19)

#define ORSTCON_PHYSWRESET 0x1
#define ORSTCON_LINKSWRESET 0x2
#define ORSTCON_PHYLINKSWRESET 0x4

#define GRSTCTL_CORESOFTRESET 0x1

#define GINTMSK_NONE 0x0
#define DIEPMSK_NONE 0x0
#define DOEPMSK_NONE 0x0

#define DCTL_SFTDISCONNECT 0x2

// ENDPOINT_DIRECTIONS register has two bits per endpoint. 0, 1 for endpoint 0. 1, 2 for end point 1, etc.
#define USB_EP_DIRECTION(ep) ((GET_REG(USB + USB_ENDPOINT_DIRECTIONS) >> ((ep) * 2)) & 0x3)
#define USB_ENDPOINT_DIRECTIONS_BIDIR 0
#define USB_ENDPOINT_DIRECTIONS_IN 1
#define USB_ENDPOINT_DIRECTIONS_OUT 2

#define USB_START_DELAYUS 10000
#define USB_RESET_DELAYUS 1000
#define USB_SFTDISCONNECT_DELAYUS 4000
#define USB_ONOFFSTART_DELAYUS 100
#define USB_PHYPWRPOWERON_DELAYUS 10
#define USB_RESET2_DELAYUS 20
#define USB_RESETWAITFINISH_DELAYUS 1000
#define USB_SFTCONNECT_DELAYUS 250

#define USB_EPINT_INEPNakEff 0x40
#define USB_EPINT_INTknEPMis 0x20
#define USB_EPINT_INTknTXFEmp 0x10
#define USB_EPINT_TimeOUT 0x8
#define USB_EPINT_AHBErr 0x4
#define USB_EPINT_EPDisbld 0x2
#define USB_EPINT_XferCompl 0x1

#define USB_EPINT_Back2BackSETup 0x40
#define USB_EPINT_OUTTknEPDis 0x10
#define USB_EPINT_SetUp 0x8

#define USB_NUM_ENDPOINTS 6

#endif

