#ifndef HW_USB_H
#define HW_USB_H

#include "hardware/s5l8900.h"

// Device
#define USB 0x38400000
#define USB_PHY 0x3C400000

// Registers
#define USB_ONOFF 0xE00

#define OPHYPWR 0
#define ORSTCON 0x8

// Values
#define USB_OTGCLOCKGATE 0x2
#define USB_PHYCLOCKGATE 0x23
#define USB_ONOFF_OFF 3 // bits 0, 1

#define OPHYPWR_FORCESUSPEND 0x1
#define OPHYPWR_PLLPOWERDOWN 0x2
#define OPHYPWR_XOPOWERDOWN 0x4
#define OPHYPWR_ANALOGPOWERDOWN 0x8
#define OPHYPWR_UNKNOWNPOWERDOWN 0x10

#define ORSTCON_PHYSWRESET 0x1
#define ORSTCON_LINKSWRESET 0x2
#define ORSTCON_PHYLINKSWRESET 0x4

#endif

